// apps/react-app/src/features/tasks/task-form.tsx
import { useState, type FormEvent } from 'react'
import {
  TASK_PRIORITIES,
  validateTaskInput,
  type FieldErrors,
  type Project,
  type Task,
  type TaskInput,
  type TaskPriority,
  type User,
} from '@operations-hub/domain'
import { Field } from '../../components/field'

export interface TaskFormProps {
  /** Present in edit mode (TSK-EDIT), absent in create mode (TSK-CREATE). */
  initial?: Task
  users: User[]
  projects: Project[]
  /** Returns true when the store accepted the mutation. */
  onSubmit(input: TaskInput): boolean
  onCancel(): void
}

export function TaskForm({ initial, users, projects, onSubmit, onCancel }: TaskFormProps) {
  const isEdit = initial !== undefined
  const [title, setTitle] = useState(initial?.title ?? '')
  const [description, setDescription] = useState(initial?.description ?? '')
  const [projectId, setProjectId] = useState(initial?.projectId ?? '')
  // TSK-CREATE-1: priority defaults to medium for new tasks.
  const [priority, setPriority] = useState<TaskPriority>(initial?.priority ?? 'medium')
  const [assigneeId, setAssigneeId] = useState(initial?.assigneeId ?? '')
  const [errors, setErrors] = useState<FieldErrors>({})
  const [submitError, setSubmitError] = useState<string | null>(null)

  const clearError = (field: string): void => {
    setErrors((current) => {
      if (current[field] === undefined) {
        return current
      }
      const next = { ...current }
      delete next[field]
      return next
    })
    setSubmitError(null)
  }

  const handleSubmit = (event: FormEvent): void => {
    event.preventDefault()
    const input: TaskInput = {
      title,
      description: description || null,
      priority,
      assigneeId: assigneeId === '' ? null : assigneeId,
      projectId,
    }
    const validationErrors = validateTaskInput(
      input,
      { users, projects },
      isEdit ? initial.status : undefined,
    )
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors)
      setSubmitError(null)
      return
    }
    setErrors({})
    if (!onSubmit(input)) {
      setSubmitError('Could not save the task. Review the form and try again.')
    }
  }

  return (
    <form className="task-form" onSubmit={handleSubmit} noValidate>
      <h3>{isEdit ? 'Edit task' : 'New task'}</h3>

      <Field id="task-title" label="Title" errors={errors.title}>
        <input
          id="task-title"
          value={title}
          onChange={(event) => {
            setTitle(event.target.value)
            clearError('title')
          }}
          aria-invalid={errors.title !== undefined}
          aria-describedby={errors.title !== undefined ? 'task-title-error' : undefined}
        />
      </Field>

      <Field id="task-description" label="Description (optional)" errors={errors.description}>
        <textarea
          id="task-description"
          value={description}
          onChange={(event) => {
            setDescription(event.target.value)
            clearError('description')
          }}
          aria-invalid={errors.description !== undefined}
          aria-describedby={errors.description !== undefined ? 'task-description-error' : undefined}
        />
      </Field>

      {!isEdit ? (
        <Field id="task-project" label="Project" errors={errors.projectId}>
          <select
            id="task-project"
            value={projectId}
            onChange={(event) => {
              setProjectId(event.target.value)
              clearError('projectId')
            }}
            aria-invalid={errors.projectId !== undefined}
            aria-describedby={errors.projectId !== undefined ? 'task-project-error' : undefined}
          >
            <option value="">Select a project</option>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.name}
              </option>
            ))}
          </select>
        </Field>
      ) : null}

      <Field id="task-priority" label="Priority" errors={errors.priority}>
        <select
          id="task-priority"
          value={priority}
          onChange={(event) => {
            setPriority(event.target.value as TaskPriority)
            clearError('priority')
          }}
          aria-invalid={errors.priority !== undefined}
          aria-describedby={errors.priority !== undefined ? 'task-priority-error' : undefined}
        >
          {TASK_PRIORITIES.map((option) => (
            <option key={option} value={option}>
              {option}
            </option>
          ))}
        </select>
      </Field>

      <Field id="task-assignee" label="Assignee (optional)" errors={errors.assigneeId}>
        <select
          id="task-assignee"
          value={assigneeId}
          onChange={(event) => {
            setAssigneeId(event.target.value)
            clearError('assigneeId')
          }}
          aria-invalid={errors.assigneeId !== undefined}
          aria-describedby={errors.assigneeId !== undefined ? 'task-assignee-error' : undefined}
        >
          <option value="">Unassigned</option>
          {users.map((user) => (
            <option key={user.id} value={user.id}>
              {user.name}
            </option>
          ))}
        </select>
      </Field>

      {submitError !== null ? (
        <p className="feedback" role="alert">
          {submitError}
        </p>
      ) : null}

      <div className="form-actions">
        <button type="submit" className="primary">
          {isEdit ? 'Save changes' : 'Create task'}
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </div>
    </form>
  )
}

// apps/angular-app/src/app/features/tasks/task-form.component.ts
import { Component, OnInit, computed, input, output, signal } from '@angular/core'
import {
  TASK_PRIORITIES,
  validateTaskInput,
  type FieldErrors,
  type Project,
  type Task,
  type TaskInput,
  type TaskPriority,
  type User,
} from '@operations-hub/domain'
import { FieldComponent } from '../../components/field.component'

@Component({
  selector: 'app-task-form',
  standalone: true,
  imports: [FieldComponent],
  templateUrl: './task-form.component.html',
})
export class TaskFormComponent implements OnInit {
  /** Present in edit mode (TSK-EDIT), absent in create mode (TSK-CREATE). */
  readonly initial = input<Task | undefined>(undefined)
  readonly users = input.required<User[]>()
  readonly projects = input.required<Project[]>()
  readonly submit = output<TaskInput>()
  readonly cancel = output<void>()

  readonly isEdit = computed(() => this.initial() !== undefined)

  readonly title = signal('')
  readonly description = signal('')
  readonly projectId = signal('')
  readonly priority = signal<TaskPriority>('medium')
  readonly assigneeId = signal('')
  readonly errors = signal<FieldErrors>({})

  readonly priorities = TASK_PRIORITIES

  ngOnInit(): void {
    const initial = this.initial()
    this.title.set(initial?.title ?? '')
    this.description.set(initial?.description ?? '')
    this.projectId.set(initial?.projectId ?? '')
    // TSK-CREATE-1: priority defaults to medium for new tasks.
    this.priority.set(initial?.priority ?? 'medium')
    this.assigneeId.set(initial?.assigneeId ?? '')
  }

  fieldErrors(field: string): string[] | undefined {
    return this.errors()[field]
  }

  hasError(field: string): boolean {
    return (this.errors()[field]?.length ?? 0) > 0
  }

  clearError(field: string): void {
    this.errors.update((current) => {
      if (current[field] === undefined) {
        return current
      }
      const next = { ...current }
      delete next[field]
      return next
    })
  }

  handleSubmit(event: Event): void {
    event.preventDefault()
    const input: TaskInput = {
      title: this.title(),
      description: this.description() || null,
      priority: this.priority(),
      assigneeId: this.assigneeId() === '' ? null : this.assigneeId(),
      projectId: this.projectId(),
    }
    const initial = this.initial()
    const validationErrors = validateTaskInput(
      input,
      { users: this.users(), projects: this.projects() },
      initial?.status,
    )
    if (Object.keys(validationErrors).length > 0) {
      this.errors.set(validationErrors)
      return
    }
    this.errors.set({})
    this.submit.emit(input)
  }
}

<form class="task-form" (submit)="handleSubmit($event)" novalidate>
  <h3>{{ isEdit() ? 'Edit task' : 'New task' }}</h3>

  <app-field [controlId]="'task-title'" label="Title" [errors]="fieldErrors('title')">
    <input
      id="task-title"
      [value]="title()"
      (input)="title.set($any($event.target).value); clearError('title')"
      [attr.aria-invalid]="hasError('title')"
      [attr.aria-describedby]="hasError('title') ? 'task-title-error' : null"
    />
  </app-field>

  <app-field
    [controlId]="'task-description'"
    label="Description (optional)"
    [errors]="fieldErrors('description')"
  >
    <textarea
      id="task-description"
      [value]="description()"
      (input)="description.set($any($event.target).value); clearError('description')"
      [attr.aria-invalid]="hasError('description')"
      [attr.aria-describedby]="hasError('description') ? 'task-description-error' : null"
    ></textarea>
  </app-field>

  @if (!isEdit()) {
    <app-field [controlId]="'task-project'" label="Project" [errors]="fieldErrors('projectId')">
      <select
        id="task-project"
        [value]="projectId()"
        (change)="projectId.set($any($event.target).value); clearError('projectId')"
        [attr.aria-invalid]="hasError('projectId')"
        [attr.aria-describedby]="hasError('projectId') ? 'task-project-error' : null"
      >
        <option value="">Select a project</option>
        @for (project of projects(); track project.id) {
          <option [value]="project.id">{{ project.name }}</option>
        }
      </select>
    </app-field>
  }

  <app-field [controlId]="'task-priority'" label="Priority" [errors]="fieldErrors('priority')">
    <select
      id="task-priority"
      [value]="priority()"
      (change)="priority.set($any($event.target).value); clearError('priority')"
      [attr.aria-invalid]="hasError('priority')"
      [attr.aria-describedby]="hasError('priority') ? 'task-priority-error' : null"
    >
      @for (option of priorities; track option) {
        <option [value]="option">{{ option }}</option>
      }
    </select>
  </app-field>

  <app-field
    [controlId]="'task-assignee'"
    label="Assignee (optional)"
    [errors]="fieldErrors('assigneeId')"
  >
    <select
      id="task-assignee"
      [value]="assigneeId()"
      (change)="assigneeId.set($any($event.target).value); clearError('assigneeId')"
      [attr.aria-invalid]="hasError('assigneeId')"
      [attr.aria-describedby]="hasError('assigneeId') ? 'task-assignee-error' : null"
    >
      <option value="">Unassigned</option>
      @for (user of users(); track user.id) {
        <option [value]="user.id">{{ user.name }}</option>
      }
    </select>
  </app-field>

  <div class="form-actions">
    <button type="submit" class="primary">{{ isEdit() ? 'Save changes' : 'Create task' }}</button>
    <button type="button" (click)="cancel.emit()">Cancel</button>
  </div>
</form>
