// apps/angular-app/src/app/features/projects/project-detail.component.ts
import { Component, computed, input, output } from '@angular/core'
import {
  PROJECT_TRANSITIONS,
  type Project,
  type ProjectStatus,
  type Task,
  type Team,
  type User,
} from '@operations-hub/domain'
import { EmptyStateComponent } from '../../components/empty-state.component'
import { PriorityBadgeComponent } from '../../components/priority-badge.component'
import { StatusBadgeComponent } from '../../components/status-badge.component'
import { TransitionButtonsComponent } from '../../components/transition-buttons.component'

@Component({
  selector: 'app-project-detail',
  standalone: true,
  imports: [
    EmptyStateComponent,
    PriorityBadgeComponent,
    StatusBadgeComponent,
    TransitionButtonsComponent,
  ],
  templateUrl: './project-detail.component.html',
})
export class ProjectDetailComponent {
  readonly project = input.required<Project>()
  readonly tasks = input.required<Task[]>()
  readonly users = input.required<User[]>()
  readonly teams = input.required<Team[]>()
  readonly transition = output<ProjectStatus>()
  readonly edit = output<void>()

  readonly owner = computed(() => this.users().find((user) => user.id === this.project().ownerId))
  readonly team = computed(() =>
    this.teams().find((candidate) => candidate.id === this.project().teamId),
  )
  readonly targets = computed<ProjectStatus[]>(
    () => PROJECT_TRANSITIONS[this.project().status] ?? [],
  )

  onTransition(target: string): void {
    this.transition.emit(target as ProjectStatus)
  }
}

<section class="project-detail" [attr.aria-label]="'Project ' + project().name">
  <div class="list-row">
    <h2 class="grow">{{ project().name }}</h2>
    <app-status-badge [status]="project().status" />
  </div>
  <p>{{ project().description ?? 'No description' }}</p>
  <p>
    Owner: <strong>{{ owner()?.name ?? project().ownerId }}</strong> · Team:
    <strong>{{ team()?.name ?? project().teamId }}</strong>
  </p>

  <div class="list-row">
    <button type="button" (click)="edit.emit()">Edit project</button>
  </div>

  <h3>Status</h3>
  <p>
    Current: <strong>{{ project().status }}</strong>
  </p>
  <app-transition-buttons
    [from]="project().status"
    [targets]="targets()"
    (transition)="onTransition($event)"
  />

  <h3>Tasks ({{ tasks().length }})</h3>
  @if (tasks().length === 0) {
    <app-empty-state message="This project has no tasks yet." />
  } @else {
    <ul class="list">
      @for (task of tasks(); track task.id) {
        <li class="list-row">
          <span class="grow">{{ task.title }}</span>
          <app-status-badge [status]="task.status" />
          <app-priority-badge [priority]="task.priority" />
        </li>
      }
    </ul>
  }
</section>

// apps/react-app/src/features/projects/project-detail.tsx
import {
  PROJECT_TRANSITIONS,
  type Project,
  type ProjectStatus,
  type Task,
  type TaskPriority,
  type TaskStatus,
  type Team,
  type User,
} from '@operations-hub/domain'
import { EmptyState } from '../../components/empty-state'
import { StatusBadge } from '../../components/status-badge'
import { PriorityBadge } from '../../components/priority-badge'
import { TransitionButtons } from '../../components/transition-buttons'

export interface ProjectDetailProps {
  project: Project
  tasks: Task[]
  users: User[]
  teams: Team[]
  onTransition(to: ProjectStatus): void
  onEdit(): void
}

export function ProjectDetail({
  project,
  tasks,
  users,
  teams,
  onTransition,
  onEdit,
}: ProjectDetailProps) {
  const owner = users.find((user) => user.id === project.ownerId)
  const team = teams.find((candidate) => candidate.id === project.teamId)
  const targets = PROJECT_TRANSITIONS[project.status] ?? []

  return (
    <section className="project-detail" aria-label={`Project ${project.name}`}>
      <div className="list-row">
        <h2 className="grow">{project.name}</h2>
        <StatusBadge status={project.status} />
      </div>
      <p>{project.description ?? 'No description'}</p>
      <p>
        Owner: <strong>{owner?.name ?? project.ownerId}</strong> · Team:{' '}
        <strong>{team?.name ?? project.teamId}</strong>
      </p>

      <div className="list-row">
        <button type="button" onClick={onEdit}>
          Edit project
        </button>
        <span className="grow" />
      </div>

      <h3>Status</h3>
      <p>
        Current: <strong>{project.status}</strong>
      </p>
      <TransitionButtons from={project.status} targets={targets} onTransition={onTransition} />

      <h3>Tasks ({tasks.length})</h3>
      {tasks.length === 0 ? (
        <EmptyState message="This project has no tasks yet." />
      ) : (
        <ul className="list">
          {tasks.map((task: Task) => (
            <li key={task.id} className="list-row">
              <span className="grow">{task.title}</span>
              <TaskMeta status={task.status} priority={task.priority} />
            </li>
          ))}
        </ul>
      )}
    </section>
  )
}

function TaskMeta({ status, priority }: { status: TaskStatus; priority: TaskPriority }) {
  return (
    <>
      <StatusBadge status={status} />
      <PriorityBadge priority={priority} />
    </>
  )
}
